### ISSUE TITLE
Not attaching probe on G28 Z from mainsail after recent updates

### ISSUE THREAD

**Issue by 53Aries** [jlas1/Klicky-Probe#248]
After updating Klipper, mainsail, moonraker, everything a few days ago and updating my Klicky probe macros.cfg the printer no longer attempts to attach the probe when using the mainsail homing buttons. When clicking Home Z the toolhead moves to the center of the bed and error is raised "Endstop z still triggered after retract". No attempt is made to attach probe. Homing and probing works fine during print start macros. I don't know if something changed in mainsail or in the klicky macros, but something changed. My full printer config can be found at https://github.com/53Aries/SPOne.1

**Comment by jlas1** [comment]
There was a klipper update the broke klicky macros, try to update to the last version and try again.

**Comment by 53Aries** [comment]
> There was a klipper update the broke klicky macros, try to update to the last version and try again.

I did update klicky along with all the other updates.

**Comment by jlas1** [comment]
try to enable klicky debug and see what's it doing.
Also, if you are using klicky as a virtual Z endstop, check if it's properly configured, klicky is able to detect that and mount the probe before homing Z

**Comment by AndyWo83** [comment]
I have almost the same problem
When the klicky probe ist attached, i have errors with ACCEL_TO_DECEL. 
This feature is deprecated and was replaced by MINIMUM_CRUISE_RATIO.
![image](https://github.com/jlas1/Klicky-Probe/assets/45575213/b2956040-3acd-4ae5-98af-96f1382b73b4)

**Comment by AndyWo83** [comment]
Here with klicky debug notifications...

14:44
Error on 'SET_VELOCITY_LIMIT ACCEL_TO_DECEL=': unable to parse
14:44
Error on 'SET_VELOCITY_LIMIT ACCEL_TO_DECEL=': unable to parse
14:44
Error on 'SET_VELOCITY_LIMIT ACCEL_TO_DECEL=': unable to parse
14:44
Error on 'SET_VELOCITY_LIMIT ACCEL_TO_DECEL=': unable to parse
14:44
Error on 'SET_VELOCITY_LIMIT ACCEL_TO_DECEL=': unable to parse
14:44
Attach_Probe moving from the dock to G0 X22 Y276 F4500
14:44
Attach_Probe moving to the dock with G0 X22 Y306 F3000
14:44
Attach_Probe moving to the dock with G0 X22 Y306 F3000
14:44
Attach_Probe moving near the dock with G0 X22 Y276 F15000
14:44
_klicky_status_busy activating the LED STATUS_BUSY
14:44
Attach_Probe going to attach probe
14:44
Attaching Probe
14:44
homing_override probe configured as a virtual Z endstop attaching probe
14:44
homing_override backing off Y endstop, G0 Y300.0 F15000
14:44
homing_override Homing Y, G28 Y0
14:44
homing_override backing off X endstop, G0 X300.0 F15000
14:44
homing_override Homing X, G28 X0
14:44
homing_override moving toolhead to 15mm from 0.0mm
14:44
homing_override no axis homed, setting position as X=Y=0 Z=0
14:44
_klicky_status_homing activating the LED STATUS_HOMING
14:44
homing_override goint to home all axes
14:44
probe: TRIGGERED
14:44
Homing Z
14:44
Homing Y
14:44
Homing X
14:44
X or Y not homed, forcing full G28
14:44
moving to a safe Z distance
14:44
No axis homed

**Comment by AndyWo83** [comment]
I've updated your macro and now it works...

```
[gcode_macro _exit_point]
gcode:
    {% set function  = 'pre_' ~ params.FUNCTION %}
    {% set move  = params.MOVE|default(0) %}
    {% set speed = printer["gcode_macro _User_Variables"].travel_speed %}

    # mandatory to save the new safe position
    M400
    SET_VELOCITY_LIMIT ACCEL={printer.configfile.settings.printer.max_accel}
    SET_VELOCITY_LIMIT MINIMUM_CRUISE_RATIO={printer.configfile.settings.printer.minimum_cruise_ratio}
    RESTORE_GCODE_STATE NAME={function} MOVE={move} MOVE_SPEED={speed}
```

**Comment by jlas1** [comment]
> I've updated your macro and now it works...
> 
> ```
> [gcode_macro _exit_point]
> gcode:
>     {% set function  = 'pre_' ~ params.FUNCTION %}
>     {% set move  = params.MOVE|default(0) %}
>     {% set speed = printer["gcode_macro _User_Variables"].travel_speed %}
> 
>     # mandatory to save the new safe position
>     M400
>     SET_VELOCITY_LIMIT ACCEL={printer.configfile.settings.printer.max_accel}
>     SET_VELOCITY_LIMIT MINIMUM_CRUISE_RATIO={printer.configfile.settings.printer.minimum_cruise_ratio}
>     RESTORE_GCODE_STATE NAME={function} MOVE={move} MOVE_SPEED={speed}
> ```

Thanks for the reply, yours is a differrent issue than the one OP has, you can solve it by updating the macros, that issue was addressed on the lastest version.

**Comment by bombsquad85** [comment]
> > I've updated your macro and now it works...
> > ```
> > [gcode_macro _exit_point]
> > gcode:
> >     {% set function  = 'pre_' ~ params.FUNCTION %}
> >     {% set move  = params.MOVE|default(0) %}
> >     {% set speed = printer["gcode_macro _User_Variables"].travel_speed %}
> > 
> >     # mandatory to save the new safe position
> >     M400
> >     SET_VELOCITY_LIMIT ACCEL={printer.configfile.settings.printer.max_accel}
> >     SET_VELOCITY_LIMIT MINIMUM_CRUISE_RATIO={printer.configfile.settings.printer.minimum_cruise_ratio}
> >     RESTORE_GCODE_STATE NAME={function} MOVE={move} MOVE_SPEED={speed}
> > ```
> 
> Thanks for the reply, yours is a differrent issue than the one OP has, you can solve it by updating the macros, that issue was addressed on the lastest version.

So I have updated my macros with the new versions on the github repository, however, I still can't home without homing x y then attach probe then Z. Did I miss a fix somewhere?

**Comment by jlas1** [comment]
you can only attach the probe after doing a G28 X and Y, so not sure on whats the issue here.
If you are using klicky as a virtual endstop and it doesn't work if you only issue a G28, then please check the "virtual endstop" configuration, you may have a space after the virtual endstop config.

Can you paste your virtual endstop config?

**Comment by bombsquad85** [comment]
> you can only attach the probe after doing a G28 X and Y, so not sure on whats the issue here. If you are using klicky as a virtual endstop and it doesn't work if you only issue a G28, then please check the "virtual endstop" configuration, you may have a space after the virtual endstop config.
> 
> Can you paste your virtual endstop config?

I can post that this afternoon when I get home.

I'll check for spaces.

**Comment by thebigone2087** [comment]
hate to necro an old issue, but I am having the same issue after freshly installing kicky on my switchwire. The probe attach and probe dock macros work perfectly on their own, and if I home X and Y then use the probe attach macro it will home z, but if I to a home all, I will get a " !! Endstop stepper_z still triggered after retract" I will attach my printer.cfg and klippy.log. 

[klippy-6.log](https://github.com/user-attachments/files/22875331/klippy-6.log)

## *** THINGS TO CHANGE/CHECK: ***
## MCU paths                         	[mcu] section
## Thermistor types                      [extruder] and [heater_bed] sections - See 'sensor types' list at end of file
## PID tune                              [extruder] and [heater_bed] sections
## Fine tune E steps                     [extruder] section

## For wiring directions please see https://docs.vorondesign.com/build/electrical/sw_miniE3_v20_wiring.html

## Webclient config files. Uncomment one depending on UI being used.
#[include mainsail.cfg]
#[include fluidd.cfg]
[include sample-bigtreetech-ebb-canbus-v1.2.cfg]
[include klicky-probe.cfg]
[include LEDS.cfg]



[printer]
kinematics: corexz
max_velocity: 200
max_accel: 1000
max_z_velocity: 50
max_z_accel: 1000
square_corner_velocity: 4.0

[mcu]
###Change to device found by "ls -l /dev/serial/by-id/" with just one this MCU connected to Pi
serial: /dev/serial/by-id/usb-Klipper_stm32g0b1xx_410021000A504B5735313920-if00

[mcu rpi]
serial: /tmp/klipper_host_mcu

[adxl345 bed]
cs_pin: rpi:None

[static_digital_output usb_pullup_enable]
pins: !PC13

[resonance_tester]
accel_chip_y: adxl345 bed
accel_chip_x: adxl345 hotend
probe_points:
    175, 175, 20  # an example
sweeping_accel: 400
sweeping_period: 0

[force_move]
enable_force_move: true

#####################################################################
# 	X Stepper Settings
#####################################################################

######
# Motor -XM
# Endstop - X-STOP
###############
[stepper_x]
step_pin: PB13
dir_pin: PB12
enable_pin: !PB14
rotation_distance: 40
full_steps_per_rotation: 200
microsteps: 32
endstop_pin: EBBCan: PB5
position_endstop: 250
position_min: 0
position_max: 250
homing_speed: 70
homing_positive_dir: true

[tmc2209 stepper_x]
uart_pin: PC11
tx_pin: PC10
uart_address: 0
run_current: 0.5
interpolate: False
stealthchop_threshold: 0

#####################################################################
#   Y Stepper Settings
#####################################################################

######
# Motor -YM
# Endstop - Y-STOP
###############
[stepper_y]
step_pin: PB10
dir_pin: PB2
enable_pin: !PB11
rotation_distance: 40
full_steps_per_rotation: 200
microsteps: 32
## Ucomment one of the following:
## Switch-based endstop for Y
#endstop_pin: ^PC1
## Sensorless endstop for Y
endstop_pin: tmc2209_stepper_y:virtual_endstop
homing_retract_dist: 0 # Uncomment this line too
position_endstop: 250
position_min: 0
position_max: 250
homing_speed: 70
homing_positive_dir: true

[tmc2209 stepper_y]
uart_pin: PC11
tx_pin: PC10
uart_address: 2
run_current: 0.7
interpolate: False
stealthchop_threshold: 0
## Uncomment if using sensorless Y homing.
driver_SGTHRS: 120 # tune this once it's working.
diag_pin: ^PC1

#####################################################################
# 	Z Stepper Settings
#####################################################################

######
# Motor -ZAM
# Endstop - Z-STOP
###############
[stepper_z]
step_pin: PB0
dir_pin: PC5
enable_pin: !PB1
rotation_distance: 40
full_steps_per_rotation: 200
microsteps: 32
endstop_pin: probe:z_virtual_endstop
position_max: 250
homing_speed: 40
position_min: -15

[tmc2209 stepper_z]
uart_pin: PC11
tx_pin: PC10
uart_address: 1
run_current: 0.5
interpolate: False
stealthchop_threshold: 0

#####################################################################
#   Extruder Settings
#####################################################################

######
#Motor - EM
###############
#[extruder]
# E0_STEP_PIN        PB3
# E0_DIR_PIN         PB4
# E0_ENABLE_PIN      PB1
# E0_UART_RX         PC11
# E0_UART_TX         PC10
#step_pin: PB3
#dir_pin: PB4
#enable_pin: !PD1
##  Update value below when you perform extruder calibration
##  If you ask for 100mm of filament, but in reality it is 98mm:
##  rotation_distance = <previous_rotation_distance> * <actual_extrude_distance> / 100
##  22.6789511 is a good starting point
#rotation_distance: 22.6789511   #Bondtech 5mm Drive Gears
##  Update Gear Ratio depending on your Extruder Type
##  Use 50:10 for Stealthburner/Clockwork 2
##  Use 50:17 for Afterburner/Clockwork (BMG Gear Ratio)
##  Use 80:20 for M4, M3.1
#gear_ratio: 50:10
#microsteps: 32
##full_steps_per_rotation: 200
#nozzle_diameter: 0.400
#filament_diameter: 1.75
#heater_pin: PC8
##  Validate the following thermistor type to make sure it is correct
##  See https://www.klipper3d.org/Config_Reference.html#common-thermistors for additional options
# sensor_type: Generic 3950
#sensor_pin: PA0
#min_temp: 10
#max_temp: 270
#max_power: 1.0
#min_extrude_temp: 170
#control = pid
#pid_kp = 26.213
#pid_ki = 1.304
#pid_kd = 131.721
#Set appropriate once tuning your printer
#pressure_advance: .05
##	Default is 0.040, leave stock
# pressure_advance_smooth_time: 0.040
#max_extrude_only_distance: 150.0

#[tmc2209 extruder]
#uart_pin: PC11
#tx_pin: PC10
#uart_address: 3
#run_current: 0.7
#hold_current: 0.3
#interpolate: False

#####################################################################
# 	Bed Heater
#####################################################################

######
# BED Connector
###############
[heater_bed]
heater_pin: PC9
##  Validate the following thermistor type to make sure it is correct
##  See https://www.klipper3d.org/Config_Reference.html#common-thermistors for additional options
sensor_type: Generic 3950
sensor_pin: PC4
min_temp: 0
max_temp: 130
#control: pid
#pid_kp: 58.437
#pid_ki: 2.347
#pid_kd: 363.769

#####################################################################
# 	Probe
#####################################################################

######
#Z Max Connector on Z(main) Board
#Inductive Probe
###############
[probe]
Pin: EBBCan:PB6
x_offset: 0
y_offset: 19.75
z_offset: 6.17
speed: 5
lift_speed: 7
samples: 3
samples_result: median
sample_retract_dist: 2
samples_tolerance: 0.01
samples_tolerance_retries: 10

[servo klicky_servo]
#check were your servo is wired
pin: PC12
maximum_servo_angle: 180
minimum_pulse_width: 0.00025
maximum_pulse_width: 0.0024

[gcode_macro _servo_test_angle]
gcode:
	{% set ANGLE  = params.ANGLE|int %}

    SET_SERVO SERVO=klicky_servo ANGLE={ANGLE}
    G4 P250
    SET_SERVO SERVO=klicky_servo WIDTH=0.0

#####################################################################
# 	Fan Control
#####################################################################

######
# Electronics Fan
# FAN1 Connector
###############
[controller_fan my_controller_fan]
pin: PC7
max_power: 1.00
kick_start_time: 0.200
heater: heater_bed

######
# Hot End Fan
# FAN2 Connector
###############
#[heater_fan extruder_fan]
#pin: PB15
#heater: extruder
#heater_temp: 50.0
##  If you are experiencing back flow, you can reduce fan_speed
#fan_speed: 1.0

######
# Part Cooling Fan
# FAN0 Connector
###############
#[fan]
#pin: PC6  # "FAN0"
#cycle_time: .08
##	Depending on your fan, you may need to increase this value
##	if your fan will not start. Can change cycle_time (increase)
##	if your fan is not able to slow down effectively
kick_start_time: .25

#####################################################################
#   Homing and Bed Mesh
#####################################################################
[homing_override]
axes: z
set_position_z: 0
gcode:
    G90
    G0 Z5 F500
    G28 X0 Y0
    G0 X125 Y100 F9000
    G28 Z0
    G0 Z5 F500

[bed_mesh]
speed: 150
horizontal_move_z: 15
mesh_min: 25,35.0
mesh_max: 225.0,220
probe_count: 6,6
algorithm: bicubic
fade_start: 1
fade_end: 10
fade_target: 0




#####################################################################
# 	Displays
#####################################################################
## 	For the mini12864 Display, the [display] and [neopixel] must be uncommented
# mini12864 LCD Display
# connected to exp1/2
#[display]
##    mini12864 LCD Display
#lcd_type: uc1701
#cs_pin: PB8
#a0_pin: PB15
#rst_pin: PB9
#encoder_pins: ^PA9,^PA10
#click_pin: ^!PB5
#contrast: 63
#spi_software_sclk_pin: PA5
#spi_software_mosi_pin: PA7
#spi_software_miso_pin: PA6
#menu_reverse_navigation: True

#[neopixel fysetc_mini12864]
##	To control Neopixel RGB in mini12864 display
## Remember with these ones, you'll need to remove the connector header on the LCD for EXT1 + 2
## (it slides off) and reverse it for it to work on your SKR (1.3 and 1.4) board
#pin: PA15
#chain_count: 3
#initial_RED: 1
#initial_GREEN: 1
#initial_BLUE: 1
#color_order: RGB

##	Set RGB values on boot up for each Neopixel.
##	Index 1 = display, Index 2 and 3 = Knob
#[delayed_gcode setdisplayneopixel]
#initial_duration: 1
#gcode:
#        SET_LED LED=fysetc_mini12864 RED=1 GREEN=1 BLUE=1 INDEX=1 TRANSMIT=0	# Backlit Screen colour
#        SET_LED LED=fysetc_mini12864 RED=1 GREEN=0 BLUE=0 INDEX=2 TRANSMIT=0	# Top left Knob colour
#        SET_LED LED=fysetc_mini12864 RED=1 GREEN=0 BLUE=0 INDEX=3				# Bottom right knob colour

#####################################################################
#   Case Lights
#####################################################################
[output_pin LIGHTS]
pin: PA8
value: 1
shutdown_value: 0

[gcode_macro lights_on]
gcode:
    SET_PIN PIN=LIGHTS VALUE=1.0

[gcode_macro lights_off]
gcode:
    SET_PIN PIN=LIGHTS VALUE=0.0


#####################################################################
# 	Macros
#####################################################################
[gcode_macro PRINT_START]
#   Use PRINT_START for the slicer starting script - please customise for your slicer of choice
gcode:
  STATUS_READY
  #{% set BED_TEMP = params.BED|default(110)|float %}
  #{% set EXTRUDER_TEMP = params.EXTRUDER|default(240)|float %}
  {% set BED_TEMP = params.BED_TEMP|int %}
  {% set EXTRUDER_TEMP = params.EXTRUDER_TEMP|int %}
  STATUS_HEATING
  M117 Preheating
  M190 S{BED_TEMP} ; wait for bed to heat to target temperature
  M109 S150 ; wait for hotend to heat to 180C - soften filament, but no oozing
  G21 ; use mmm
  G90 ; use absolute coordinates
  M82 ; extruder relative mode
  #G1 E-10.0 F3600
  G28 ; home all axes
  G0 X115 Y115 Z10 F4000 ; move toolhead to centre
  ; wait for heat soak
  #G32
  #BED_MESH_CALIBRATE
  BED_MESH_PROFILE LOAD=default
  STATUS_CLEANING
  #G0 X105 Y300 Z10 F9000 ; move to startpoint of purgebucket
  STATUS_HEATING
  M117 Heating to target temp
  M109 S{EXTRUDER_TEMP} ; wait for hotend to get to target temperature
  #G0 X115 Y5 Z10 F9000 ; move to startpoint of purgeline
  #PURGE_LINE
  STATUS_BUSY


[gcode_macro PRINT_END]
#   Use PRINT_END for the slicer ending script
gcode:
    #   Get Boundaries
    {% set max_x = printer.configfile.config["stepper_x"]["position_max"]|float %}
    {% set max_y = printer.configfile.config["stepper_y"]["position_max"]|float %}
    {% set max_z = printer.configfile.config["stepper_z"]["position_max"]|float %}

    #   Check end position to determine safe directions to move
    {% if printer.toolhead.position.x < (max_x - 20) %}
        {% set x_safe = 20.0 %}
    {% else %}
        {% set x_safe = -20.0 %}
    {% endif %}

    {% if printer.toolhead.position.y < (max_y - 20) %}
        {% set y_safe = 20.0 %}
    {% else %}
        {% set y_safe = -20.0 %}
    {% endif %}

    {% if printer.toolhead.position.z < (max_z - 2) %}
        {% set z_safe = 2.0 %}
    {% else %}
        {% set z_safe = max_z - printer.toolhead.position.z %}
    {% endif %}

    #  Commence PRINT_END
    M400                             ; wait for buffer to clear
    G92 E0                           ; zero the extruder
    G1 E-4.0 F3600                   ; retract
    G91                              ; relative positioning
    G0 Z{z_safe} F3600               ; move nozzle up
    G0 X{x_safe} Y{y_safe} F20000    ; move nozzle to remove stringing

    M104 S0                          ; turn off hotend
    M140 S0                          ; turn off bed
    M106 S0                          ; turn off fan
    G90                              ; absolute positioning
    G0 X{max_x / 2} Y{max_y} F3600   ; park nozzle at rear
    M117 Finished!

[gcode_macro LOAD_FILAMENT]
variable_load_distance:  150
variable_purge_distance:  25
gcode:
    {% set speed = params.SPEED|default(150) %}
    {% set max_velocity = printer.configfile.settings['extruder'].max_extrude_only_velocity  * 60 %}
    SAVE_GCODE_STATE NAME=load_state
    G91
    G92 E0
    G1 E{load_distance} F{max_velocity} # fast-load
    G1 E{purge_distance} F{speed} # purge
    RESTORE_GCODE_STATE NAME=load_state

[gcode_macro UNLOAD_FILAMENT]
variable_unload_distance:  140
variable_purge_distance:  10
gcode:
    {% set speed = params.SPEED|default(150) %}
    {% set max_velocity = printer.configfile.settings['extruder'].max_extrude_only_velocity  * 60 %}
    SAVE_GCODE_STATE NAME=unload_state
    G91
    G92 E0
    G1 E{purge_distance} F{speed} # purge
    G1 E-{unload_distance} F{max_velocity} # fast-unload
    RESTORE_GCODE_STATE NAME=unload_state

[gcode_macro PAUSE]
description: Pause the actual running print
rename_existing: PAUSE_BASE
# change this if you need more or less extrusion
variable_extrude: 1.0
gcode:
  ##### read E from pause macro #####
  {% set E = printer["gcode_macro PAUSE"].extrude|float %}
  ##### set park positon for x and y #####
  # default is your max posion from your printer.cfg
  {% set x_park = printer.toolhead.axis_maximum.x|float - 5.0 %}
  {% set y_park = printer.toolhead.axis_maximum.y|float - 5.0 %}
  ##### calculate save lift position #####
  {% set max_z = printer.toolhead.axis_maximum.z|float %}
  {% set act_z = printer.toolhead.position.z|float %}
  {% if act_z < (max_z - 2.0) %}
      {% set z_safe = 2.0 %}
  {% else %}
      {% set z_safe = max_z - act_z %}
  {% endif %}
  ##### end of definitions #####
  PAUSE_BASE
  G91
  {% if printer.extruder.can_extrude|lower == 'true' %}
    G1 E-{E} F2100
  {% else %}
    {action_respond_info("Extruder not hot enough")}
  {% endif %}
  {% if "xyz" in printer.toolhead.homed_axes %}
    G1 Z{z_safe} F900
    G90
    G1 X{x_park} Y{y_park} F6000
  {% else %}
    {action_respond_info("Printer not homed")}
  {% endif %}

[gcode_macro RESUME]
description: Resume the actual running print
rename_existing: RESUME_BASE
gcode:
  ##### read E from pause macro #####
  {% set E = printer["gcode_macro PAUSE"].extrude|float %}
  #### get VELOCITY parameter if specified ####
  {% if 'VELOCITY' in params|upper %}
    {% set get_params = ('VELOCITY=' + params.VELOCITY)  %}
  {%else %}
    {% set get_params = "" %}
  {% endif %}
  ##### end of definitions #####
  {% if printer.extruder.can_extrude|lower == 'true' %}
    G91
    G1 E{E} F2100
  {% else %}
    {action_respond_info("Extruder not hot enough")}
  {% endif %}
  RESUME_BASE {get_params}

[gcode_macro CANCEL_PRINT]
description: Cancel the actual running print
rename_existing: CANCEL_PRINT_BASE
gcode:
  TURN_OFF_HEATERS
  CANCEL_PRINT_BASE

[gcode_macro TEST_SPEED]
# Home, get position, throw around toolhead, home again.
# If MCU stepper positions (first line in GET_POSITION) are greater than a full step different (your number of microsteps), then skipping occured.
# We only measure to a full step to accomodate for endstop variance.
# Example: TEST_SPEED SPEED=300 ACCEL=5000 ITERATIONS=10

description: Test for max speed and acceleration parameters for the printer. Procedure: Home -> ReadPositionFromMCU -> MovesToolhead@Vel&Accel -> Home -> ReadPositionfromMCU

gcode:
    # Speed
    {% set speed  = params.SPEED|default(printer.configfile.settings.printer.max_velocity)|int %}
    # Iterations
    {% set iterations = params.ITERATIONS|default(5)|int %}
    # Acceleration
    {% set accel  = params.ACCEL|default(printer.configfile.settings.printer.max_accel)|int %}
    # Minimum Cruise Ratio
    {% set min_cruise_ratio = params.MIN_CRUISE_RATIO|default(0.5)|float %}
    # Bounding inset for large pattern (helps prevent slamming the toolhead into the sides after small skips, and helps to account for machines with imperfectly set dimensions)
    {% set bound = params.BOUND|default(20)|int %}
    # Size for small pattern box
    {% set smallpatternsize = SMALLPATTERNSIZE|default(20)|int %}

    # Large pattern
        # Max positions, inset by BOUND
        {% set x_min = printer.toolhead.axis_minimum.x %}
        {% if x_min < 0 %}
            {% set x_min = 0 %}
        {% endif %}

        {% set y_min = printer.toolhead.axis_minimum.y %}
        {% if y_min < 0 %}
            {% set y_min = 0 %}
        {% endif %}

        {% set x_min = x_min + bound %}
        {% set x_max = printer.toolhead.axis_maximum.x - bound %}
        {% set y_min = y_min + bound %}
        {% set y_max = printer.toolhead.axis_maximum.y - bound %}

    # Small pattern at center
        # Find X/Y center point
        {% set x_center = (printer.toolhead.axis_minimum.x|float + printer.toolhead.axis_maximum.x|float ) / 2 %}
        {% set y_center = (printer.toolhead.axis_minimum.y|float + printer.toolhead.axis_maximum.y|float ) / 2 %}

        # Set small pattern box around center point
        {% set x_center_min = x_center - (smallpatternsize/2) %}
        {% set x_center_max = x_center + (smallpatternsize/2) %}
        {% set y_center_min = y_center - (smallpatternsize/2) %}
        {% set y_center_max = y_center + (smallpatternsize/2) %}

    # Save current gcode state (absolute/relative, etc)
    SAVE_GCODE_STATE NAME=TEST_SPEED

    # Output parameters to g-code terminal
    { action_respond_info("TEST_SPEED: starting %d iterations at speed %d, accel %d" % (iterations, speed, accel)) }

    # Home and get position for comparison later:
        M400 # Finish moves - https://github.com/AndrewEllis93/Print-Tuning-Guide/issues/66
        G28
        # QGL if not already QGLd (only if QGL section exists in config)
        {% if printer.configfile.settings.quad_gantry_level %}
            {% if printer.quad_gantry_level.applied == False %}
                QUAD_GANTRY_LEVEL
                G28 Z
            {% endif %}
        {% endif %}
        # Move 50mm away from max position and home again (to help with hall effect endstop accuracy - https://github.com/AndrewEllis93/Print-Tuning-Guide/issues/24)
        G90
        G1 X{printer.toolhead.axis_maximum.x-50} Y{printer.toolhead.axis_maximum.y-50} F{30*60}
        M400 # Finish moves - https://github.com/AndrewEllis93/Print-Tuning-Guide/issues/66
        G28 X Y
        G0 X{printer.toolhead.axis_maximum.x-1} Y{printer.toolhead.axis_maximum.y-1} F{30*60}
        G4 P1000
        GET_POSITION

    # Go to starting position
    G0 X{x_min} Y{y_min} Z{bound + 10} F{speed*60}

    # Set new limits
    {% if printer.configfile.settings.printer.minimum_cruise_ratio is defined %}
        SET_VELOCITY_LIMIT VELOCITY={speed} ACCEL={accel} MINIMUM_CRUISE_RATIO={min_cruise_ratio}
    {% else %}
        SET_VELOCITY_LIMIT VELOCITY={speed} ACCEL={accel} ACCEL_TO_DECEL={accel / 2}
    {% endif %}

    {% for i in range(iterations) %}
        # Large pattern diagonals
        G0 X{x_min} Y{y_min} F{speed*60}
        G0 X{x_max} Y{y_max} F{speed*60}
        G0 X{x_min} Y{y_min} F{speed*60}
        G0 X{x_max} Y{y_min} F{speed*60}
        G0 X{x_min} Y{y_max} F{speed*60}
        G0 X{x_max} Y{y_min} F{speed*60}

        # Large pattern box
        G0 X{x_min} Y{y_min} F{speed*60}
        G0 X{x_min} Y{y_max} F{speed*60}
        G0 X{x_max} Y{y_max} F{speed*60}
        G0 X{x_max} Y{y_min} F{speed*60}

        # Small pattern diagonals
        G0 X{x_center_min} Y{y_center_min} F{speed*60}
        G0 X{x_center_max} Y{y_center_max} F{speed*60}
        G0 X{x_center_min} Y{y_center_min} F{speed*60}
        G0 X{x_center_max} Y{y_center_min} F{speed*60}
        G0 X{x_center_min} Y{y_center_max} F{speed*60}
        G0 X{x_center_max} Y{y_center_min} F{speed*60}

        # Small pattern box
        G0 X{x_center_min} Y{y_center_min} F{speed*60}
        G0 X{x_center_min} Y{y_center_max} F{speed*60}
        G0 X{x_center_max} Y{y_center_max} F{speed*60}
        G0 X{x_center_max} Y{y_center_min} F{speed*60}
    {% endfor %}

    # Restore max speed/accel/accel_to_decel to their configured values
    {% if printer.configfile.settings.printer.minimum_cruise_ratio is defined %}
        SET_VELOCITY_LIMIT VELOCITY={printer.configfile.settings.printer.max_velocity} ACCEL={printer.configfile.settings.printer.max_accel} MINIMUM_CRUISE_RATIO={printer.configfile.settings.printer.minimum_cruise_ratio}
    {% else %}
        SET_VELOCITY_LIMIT VELOCITY={printer.configfile.settings.printer.max_velocity} ACCEL={printer.configfile.settings.printer.max_accel} ACCEL_TO_DECEL={printer.configfile.settings.printer.max_accel_to_decel}
    {% endif %}

    # Re-home and get position again for comparison:
        M400 # Finish moves - https://github.com/AndrewEllis93/Print-Tuning-Guide/issues/66
        G28 # This is a full G28 to fix an issue with CoreXZ - https://github.com/AndrewEllis93/Print-Tuning-Guide/issues/12
        # Go to XY home positions (in case your homing override leaves it elsewhere)
        G90
        G0 X{printer.toolhead.axis_maximum.x-1} Y{printer.toolhead.axis_maximum.y-1} F{30*60}
        G4 P1000
        GET_POSITION

    # Restore previous gcode state (absolute/relative, etc)
    RESTORE_GCODE_STATE NAME=TEST_SPEED


[virtual_sdcard]
path: /home/rpi/printer_data/gcodes

[display_status]
[pause_resume]

[exclude_object]


#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
#*#
#*# [heater_bed]
#*# control = pid
#*# pid_kp = 61.457
#*# pid_ki = 1.104
#*# pid_kd = 855.020
#*#
#*# [probe]
#*# z_offset = 11.350
#*#
#*# [bed_mesh default]
#*# version = 1
#*# points =
#*# 	-0.025000, -0.087500, -0.100000, -0.087500, -0.050000, 0.000000
#*# 	-0.056250, 0.012500, -0.087500, -0.031250, 0.018750, 0.018750
#*# 	-0.187500, -0.112500, -0.075000, 0.050000, 0.031250, 0.025000
#*# 	-0.381250, -0.281250, -0.156250, 0.012500, 0.018750, -0.006250
#*# 	-0.381250, -0.300000, -0.200000, -0.068750, -0.018750, -0.006250
#*# 	-0.343750, -0.325000, -0.250000, -0.168750, -0.093750, -0.087500
#*# x_count = 6
#*# y_count = 6
#*# mesh_x_pps = 2
#*# mesh_y_pps = 2
#*# algo = bicubic
#*# tension = 0.2
#*# min_x = 25.0
#*# max_x = 225.0
#*# min_y = 35.0
#*# max_y = 220.0
#*#
#*# [input_shaper]
#*# shaper_type_x = mzv
#*# shaper_freq_x = 63.0
#*# shaper_type_y = mzv
#*# shaper_freq_y = 42.2
